### ISSUE TITLE
假如我要拦截替换加载本地的图片文件,要怎么写呢?

### ISSUE THREAD

**Issue by hziKen** [sunzhongliangde/WKWebViewRequestHook#1]

**Comment by sunzhongliangde** [comment]
拦截到之后，转发的是一个NSURLRequest，这里url改为本地即可.

**Comment by sunzhongliangde** [comment]
NSString *pathString = [[NSBundle mainBundle] pathForResource:@"WX20191126-164229" ofType:@"png"];

mutableReqeust.URL = [NSURL fileURLWithPath:pathString];
